version: "3.8"

services:
  backend:
    container_name: dev-bas-project-backend
    build:
      context: ./backend
    volumes:
      - ./backend/:/usr/src/app/
    ports:
      - 8009:8000
    depends_on:
      - db
  db:
    container_name: dev-base-project-db
    image: postgres
    hostname: db
    environment:
      POSTGRES_PASSWORD: "bad_password"
    volumes:
      - pg_data:/var/lib/postgresql/data
volumes:
  pg_data:
